# Generated by Django 5.0.6 on 2024-06-07 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='is_company',
        ),
        migrations.AddField(
            model_name='customer',
            name='price',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
