# Generated by Django 5.0.6 on 2024-06-10 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0004_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default=0.0, max_digits=12),
            preserve_default=False,
        ),
    ]
