# Generated by Django 5.0.6 on 2024-06-19 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bot', '0007_remove_customer_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='latitude',
            field=models.DecimalField(decimal_places=9, default='0.0', max_digits=12),
        ),
        migrations.AlterField(
            model_name='customer',
            name='longitude',
            field=models.DecimalField(decimal_places=9, default='0.0', max_digits=12),
        ),
    ]
