# Generated by Django 5.0.6 on 2024-06-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(unique=True)),
                ('phone', models.CharField(max_length=14)),
                ('name', models.CharField(max_length=255)),
                ('is_company', models.BooleanField(default=False)),
                ('lang', models.PositiveSmallIntegerField(choices=[(1, 'English'), (2, 'Uzbek'), (3, 'Russian')], default=2)),
            ],
        ),
    ]
